# Generated by Django 4.1.5 on 2023-01-18 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sekolah',
            name='fax',
        ),
        migrations.AddField(
            model_name='sekolah',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sekolah_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sekolah',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='Status',
            field=models.CharField(choices=[('Swasta', 'Swasta'), ('Negeri', 'Negeri')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='kabupaten_kota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='provinsi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
