# Generated by Django 4.1.5 on 2023-01-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_sekolah_siswa_sekolah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='sekolah',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='sekolah',
        ),
    ]
