# Generated by Django 4.1.5 on 2023-01-22 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siswa', '0003_alter_siswa_sekolah_delete_sekolah'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
